### ISSUE TITLE
Enable ledger to be looked up from account identifier

### ISSUE THREAD

**Issue by emschwartz** [interledger/five-bells-ledger#105]
Right now when doing pathfinding we need to pass `source_account`, `source_ledger` and `source_username`, even though `source_account` combines the two other pieces of information. We're supposed to treat URIs as opaque so we can't assume that we can parse the username or ledger from the `source_account`.

My proposal would be to allow anyone (without authentication) to `GET` the account URI and return an object that contains the `ledger` and `account`.

One thing that would enable would be that your "account" that you share with people could actually be a service not tied to your ledger that would return your up to date payment info. If the standard behavior was for people to `GET` that endpoint first, you'd be able to update what that points to whenever you want to switch where you hold your money. This would be very useful for cases when you want to embed payment information in some data that can't be easily updated when you move accounts.

The first potential problem with this is that that endpoint would become a target for hackers because if they could change where that points to they could redirect where your money goes.

The second potential problem is that you might not want anyone to be able to find out if an account exists. That could be addressed by adding functionality to the ledgers to enable account holders to create aliases for their account that they could give to specific parties.

**Comment by justmoon** [comment]
I could have sworn I already opened this ticket. Must have forgotten to click Submit or something. :D

I know we previously decided that we didn't want to leak information, but checking an account's existence by id is important also when you're trying to send to that account. You don't want to do a bunch of work just to find out that the destination is bogus.

And of course as you point out it's needed to close tickets like interledger/five-bells-connector#51

**Comment by sentientwaffle** [comment]
> My proposal would be to allow anyone (without authentication) to GET the account URI and return an object that contains the ledger and account.

I already have this mostly implemented locally as part of https://github.com/interledger/five-bells-connector/issues/51
