### ISSUE TITLE
LEDGER_DB_SYNC issue

### ISSUE THREAD

**Issue by vhpoet** [interledger/five-bells-ledger#291]
Restarting the ledger that has a `LEDGER_DB_SYNC` environment variable throws an exception

```
CREATE INDEX "L_XPK_ACCOUNTS" ON "L_ACCOUNTS"
  ("ACCOUNT_ID" ASC) - relation "L_XPK_ACCOUNTS" already exists
```

P. S. `LEDGER_DB_SYNC` is not documented

**Comment by clark800** [comment]
This is expected behavior; you should only run with `LEDGER_DB_SYNC` set on the first time you use a particular database. Maybe we can use this issue as a documentation issue to document this.

**Comment by vhpoet** [comment]
Thanks for documenting it, now we need to think about changing the name. `LEDGER_DB_SYNC` doesn't reflect what it does. It should maybe be `LEDGER_DB_INIT`.

**Comment by clark800** [comment]
I think the term "sync" was chosen so that it is general enough to encompass migrations when we implement them in the future

**Comment by vhpoet** [comment]
ok :)
