### ISSUE TITLE
Not validating ed25519 fulfillments against the message?

### ISSUE THREAD

**Issue by emschwartz** [interledger/five-bells-ledger#312]
Found by @inacali in https://github.com/interledger/five-bells-condition/issues/51

[`cc.validateFulfillment`](https://github.com/interledger/five-bells-condition/blob/master/index.js#L23) expects a message to be passed in as the last parameter but the [ledger is only passing the fulfillment and condition](https://github.com/interledger/five-bells-ledger/blob/master/src/models/transfers.js#L300). This results in a `ValidationError: Invalid ed25519 signature` error when you try to submit the fulfillment.

**Comment by justmoon** [comment]
No, the message parameter is optional and should only be provided if you're using crypto-conditions to validate a signature over some message. `five-bells-ledger` is using it to verify a condition as a trigger, so not passing a message (which implies the empty buffer as the message) is correct.
