### ISSUE TITLE
Add ability for admin to disable accounts

### ISSUE THREAD

**Issue by justmoon** [interledger/five-bells-ledger#75]
Since account deletion would rewrite history, the alternative is to disable accounts. Disabled accounts are not able to send or receive transfers. They do not count as valid users who can authenticate. Without authentication they are unable to see their own balance, or change any properties of their account. Disabled accounts should not be included in the planned `/connectors` endpoint.

Existing transfers involving disabled accounts in their debits or credits may not be prepared. Transfers that are already prepared should complete normally, even when they involve disabled accounts.

Only admins can disable or re-enable accounts.

**Comment by MatthewPhinney** [comment]
One way to address this is to modify the existing `PUT /accounts/:id` endpoint to take a boolean `disabled` flag in the JSON body (this requires updating the db and the account schema).  This endpoint is already only available to admin users.  The only pitfall is that this endpoint requires `name` and `balance` so the admin would have to be careful not to update these fields when flipping the `disabled` flag.  The remaining logic (allowing transfers that have been prepared to execute, but disallowing future transfers) would be straightforward to implement.

This seems cleaner than adding a whole new endpoint to disable/enable accounts.
