### ISSUE TITLE
Ability to request back notifications

### ISSUE THREAD

**Issue by justmoon** [interledger/five-bells-ledger#82]
When sending out notifications, the ledger should also allow GET requests back at an URL of the form `GET /subscriptions/:id/notifications/:id`. This provides another way for a client to check if a notification is authentic, other than HTTP-Signature (#81) which may be difficult to verify in some languages where no preexisting implementation is available.

Notifications are already persisted in the database. For now we can leave that as is: The rule could be, a client who is verifying a notification must request it *before* they respond to the notification POST request. That way, the database row will still exist. In the future we may want to persist notifications longer and clean them up after some delay.

**Request:**
``` http
GET /subscriptions/52a42d6f-8d9c-4c05-b31c-cccc8bbdb30d/notifications/140
```

**Response:**
``` js
{
  "id": "http://eur-ledger.example/subscriptions/52a42d6f-8d9c-4c05-b31c-cccc8bbdb30d/notifications/140",
  "subscription": "http://eur-ledger.example/subscriptions/52a42d6f-8d9c-4c05-b31c-cccc8bbdb30d",
  "event": "transfer.update",
  "resource": {
    // ...
  }
}
```

**Comment by MatthewPhinney** [comment]
Added here: https://github.com/interledger/five-bells-ledger/commit/07d8e6b5c977e501889e4fd5936b1d51a0f48762
