### ISSUE TITLE
Notification IDs are leaking information

### ISSUE THREAD

**Issue by justmoon** [interledger/five-bells-ledger#83]
After #80, notification IDs will be public. The notification ID is currently a serial integer. This means it's leaking information about the number of notifications that are happening.

We should change that to some kind of unique ID. Could be a UUID or a shorter time-based ID like [Snowflake](https://www.npmjs.com/package/flake-idgen).

**Comment by rec** [comment]
What about a hash of the notification contents and timestamp?

**Comment by justmoon** [comment]
That would work as well.

Ideally, we want something that's unique and as small as possible. For the timestamp you need at least 32 bits, better a little more. Snowflake uses a 42-bit timestamp, a 10 bit node id and a 12-bit counter. This ensures uniqueness and only costs 64 bits total. In a distributed system it's very hard/expensive to create a counter, but by adding the 10-bit node id, you basically have a separate counter for each running worker. And by putting the timestamp first, we can use the ID both for identification as well as sorting (i.e. give me the most recent notification.) 

Using a hash is pretty much equivalent to using random bits. So for instance we could use a 32-bit timestamp and a 32-bit hash. Collisions would be pretty unlikely, but not to the "astronomically unlikely" degree that for instance a UUIDv4 (with 126 bits of randomness) gives you.

Twitter's solution (Snowflake) is minimal, elegant, available as a preexisting module and makes collisions impossible (not just unlikely.) So it seems like a good option.

**Comment by rec** [comment]
A 10-bit node ID means a maximum of 1024 nodes, which might not be a desirable limit to have hardcoded...?

**Comment by MatthewPhinney** [comment]
Where is the notification ID a serial integer? Is this a key in some DB? #80 calls for using an identifier, but it looks like the identifier is generated by the ledger, in which case we could use any unique ID (read: Snowflake, not serial int). Can we combine this issue and #80 into a single issue?

**Comment by MatthewPhinney** [comment]
Never mind, my local copy was out of date ... I didn't have the `notifications` table.

**Comment by MatthewPhinney** [comment]
https://github.com/MatthewPhinney/five-bells-ledger/commit/da97062488478a9b4925feac0a2fb9b35ce91e8b
