### ISSUE TITLE
Add pretend_state to `/transfers/:id/state` for preimage algorithms

### ISSUE THREAD

**Issue by sentientwaffle** [interledger/five-bells-ledger#89]

**Comment by clark800** [comment]
I can't find anything about this in the spec. Can you add a description explaining what "pretend_state" is and what "preimage algorithms" are?

**Comment by sentientwaffle** [comment]
preimage algorithms refer to Conditions that use hashes, such as `HashSha256Condition`.
`pretend_state` is a way for a sender to request that the ledger generate a hash of the given state (i.e. `"executed"` or `"rejected"`). Then that hash can be used in a `Condition`. The hash would include some stored or deterministic secret that only the ledger knows, so that only it can fulfill the condition.

**Comment by clark800** [comment]
Can you explain what it means for a condition to use a hash? What is the "given state"? Why is it called "pretend"?

**Comment by sentientwaffle** [comment]
Right now we are using `Ed25519_Sha512_Condition`. To fulfill the condition, the ledger with the appropriate key pair signs the hash of the message_id+state, and anyone can verify the signature.

With `HashSha256Condition`, a Condition is `hash(message_id, state, [some secret known only to the fulfilling ledger])`. The sender needs some way of getting this condition from the ledger so that it can be attached to the Transfers (and Cases, in atomic mode).

It's "pretend" because at the time the sender requests the hash from the ledger, the state that it needs the hash of is _not_ the same as the current state. It does no good to get the hash in the "nonexistent" state -- an receipt condition needs a hash of state=`executed` (or, in the case of atomic mode, `prepared`).

**Comment by clark800** [comment]
So by "preimage signature scheme" you mean HMAC? What is the advantage of this over ed25519 signing?

**Comment by sentientwaffle** [comment]
Yes, HMAC. The advantage is that it will allow compatibility with bitcoin.

**Comment by emschwartz** [comment]
That's actually not an HMAC. An HMAC is computed on a secret key and a
message.

A hash preimage condition is one where the "condition" is a straight hash
of some arbitrary message. The correct fulfillment of that condition is the
preimage for that hash. This is a type of one time signature scheme

On Mon, Jan 11, 2016 at 10:07 PM, djg <notifications@github.com> wrote:

> Yes, HMAC. The advantage is that it will allow compatibility with bitcoin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/interledger/five-bells-ledger/issues/89#issuecomment-170689951>
> .
>



-- 
Evan Schwartz | Software Architect | Ripple
[image: ripple.com] <http://ripple.com>

**Comment by clark800** [comment]
Wouldn't the arbitrary message have to have a secret component? Otherwise anyone could search the message space. And if so, then aren't we effectively talking about using HMAC as a signature? Are there any links to literature on this subject? I'm also interested in learning about how this will work with Bitcoin in more detail.

**Comment by MatthewPhinney** [comment]
Can someone provide a concrete example of how this fits into the current flow? I'm also kind of confused by the secret/no secret conversation, so more detail there would be helpful.

**Comment by sentientwaffle** [comment]
@clark800:
> Condition is `hash(message_id, state, [some secret known only to the fulfilling ledger])`

so yes, there is a secret component.

@MatthewPhinney there is a secret component to the hash because otherwise anyone could generate the preimage of the hash at any time, prematurely executing the the transaction.

As for how this fits into the flow, `HashSha256Condition` is an alternative Condition mechanism, an alternative to the currently used `Ed25519_Sha512_Condition`.

In atomic mode, the receipt condition is needed in advance of the transfer's creation so that the corresponding Case can be created in the notary (the Case requires the receipt condition). Hash conditions aren't currently implemented, but when they are, we will need a way to generate one for a given state -- the `pretend_state`.
