### ISSUE TITLE
Use consistent name for "id/name" of account

### ISSUE THREAD

**Issue by clark800** [interledger/five-bells-ledger#97]
To prevent cases like this: https://github.com/interledger/five-bells-ledger/blob/master/src/models/account.js#L20

**Comment by emschwartz** [comment]
I believe that's like that because ID is a full URI and the name is just the part that (in our case but not necessarily in the general case) follows the `http://ledger.example/accounts/` part of the URI

**Comment by clark800** [comment]
What about in this case, is the "id" supposed to be the full URI here? https://github.com/interledger/five-bells-ledger/pull/96/files

**Comment by emschwartz** [comment]
That actually might be a case where the URI param ought to be renamed to
`:name`

On Wed, Jan 13, 2016 at 6:55 PM, Chris Clark <notifications@github.com>
wrote:

> What about in this case, is the "id" supposed to be the full URI here?
> https://github.com/interledger/five-bells-ledger/pull/96/files
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/interledger/five-bells-ledger/issues/97#issuecomment-171379174>
> .
>



-- 
Evan Schwartz | Software Architect | Ripple
[image: ripple.com] <http://ripple.com>

**Comment by MatthewPhinney** [comment]
Looks like the docs already renamed the URL param to `name`. I'll make the change in the code.
