### ISSUE TITLE
Implement auth for subscriptions

### ISSUE THREAD

**Issue by MatthewPhinney** [interledger/five-bells-ledger#99]
We need to implement a permissions scheme so that only users who own an account can subscribe to events for that account.  For the code, see <a href="https://github.com/interledger/five-bells-ledger/blob/master/src/controllers/subscriptions.js#L25">here</a>.

@justmoon Should admin users be allowed to subscribe to events on any account?

**Comment by MatthewPhinney** [comment]
We also need to implement auth for the DELETE endpoint. Currently any user can delete any subscription. The user should only be allowed to delete a subscription if they are the owner (or have authorization from the owner, or are an admin).

**Comment by emschwartz** [comment]
In this vein, a nice to have feature would be a way to allow a server that
you don't entirely trust to subscribe to notifications on your behalf.
Alternatively, the ledger UI could have a way to manually setup a
subscription for that case

On Wed, Jan 13, 2016 at 2:09 AM, Matthew Phinney <notifications@github.com>
wrote:

> We also need to implement auth for the DELETE endpoint. Currently any user
> can delete any subscription. The user should only be allowed to delete a
> subscription if they are the owner (or have authorization from the owner,
> or are an admin).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/interledger/five-bells-ledger/issues/99#issuecomment-171119525>
> .
>



-- 
Evan Schwartz | Software Architect | Ripple
[image: ripple.com] <http://ripple.com>
